[package]
name = "day12-rust-password-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.3"
base64 = "0.22.1"
clap = "4"
rand_core = "0.9.3"
rpassword = "7.4.0"
serde = "1.0.228"
serde_json = "1.0.145"
